<?php

/**
 * Implements hook_entity_info_alter()
 */
/*
function taxonomy_link_redirect_entity_info_alter(&$entity_info) {
  $entity_info['taxonomy_term']['uri callback'] = '_taxonomy_link_redirect_taxonomy_term_uri';
  //dpm($entity_info);
}

function _taxonomy_link_redirect_taxonomy_term_uri($term) {
  dpm($term);
}
 */

function taxonomy_link_redirect_views_pre_render($view) {
  //dpm($view);
  $url = '/our-science';
  $page_ids = array();
  foreach($view->result as $result) {
    $node = node_load($result->nid);
    $props = get_object_vars($node);
    $fields = _taxonomy_link_redirect_distill_fields($props);
    dpm($fields);
    //$all_terms = _taxonomy_link_redirect_all_terms($node, $fields);

    //$terms = taxonomy_node_get_terms($node);
    //dpm($node);
  /*
    $fields = _taxonomy_link_redirect_distill_fields($props);
    dpm($fields);
    //dpm($props);
    //$wrapper = entity_metadata_wrapper('node', $node);
    //dpm($wrapper->getBundle());
    //if(_taxonomy_link_redirect_is_science_field($node)
   */
  }
}

function _taxonomy_link_redirect_all_terms($node, $fields) {
}
/*
 */
function _taxonomy_link_redirect_distill_fields($fields) {
  $results = array();
  foreach($fields as $key => $field) {
    if(is_array($field) && !empty($field)) {
      if(_taxonomy_link_redirect_is_science_field($key) && !in_array($key, $results)) {
        $results[] = $key;
      }
    }
  }
  //dpm(array_keys($fields));
  /*
  foreach($fields as $field) {
    //if(is_array($field) && _taxonomy_link_redirect_is_science_field(key($field))) {
    if(is_array($field) ) {
      dpm(key($field));
      //$results[] = _taxonomy_link_redirect_clean_field($field);
    }
  }
  */
  return $results;
}

function _taxonomy_link_redirect_is_science_field($field) {
  $pattern = "/^field_/";
  $title_field = 'field_title_tag';
  /*
  $to_filter = array(
    'field_science_category',
    'field_title_tag'
  );
   */
  return (preg_match($pattern, $field) === 1) && ($field != $title_field);
}


/*
function _taxonomy_link_redirect_clean($str) {
  $strip_field = str_replace('field_', '', $str);
  $url_ready = str_replace('_', '-', $strip_field);
  $clean = substr_replace($str, '', 0, 6);
  $clean = 
  return $url_ready;
}
  */
