<?php

/**
 * Implements hook_entity_info_alter()
 */
/*
function taxonomy_link_redirect_entity_info_alter(&$entity_info) {
  $entity_info['taxonomy_term']['uri callback'] = '_taxonomy_link_redirect_taxonomy_term_uri';
  //dpm($entity_info);
}

function _taxonomy_link_redirect_taxonomy_term_uri($term) {
  dpm($term);
}
 */

function taxonomy_link_redirect_views_pre_render($view) {
  //dpm($view);
  $url = '/our-science';
  $page_ids = array();
  foreach($view->result as $result) {
    $node = node_load($result->nid);
    $props = get_object_vars($node);
    $fields = _taxonomy_link_redirect_distill_fields($props);
    $terms = _taxonomy_link_redirect_all_terms($node, $fields);
    dpm($terms);
  }
}

function _taxonomy_link_redirect_all_terms($node, $fields) {
  $terms = array();
  foreach($fields as $field) {
    $vals = $node->$field;
    $vals = $vals['und'];
    foreach($vals as $val) {
      $term = taxonomy_term_load($val['tid']);
      if(!in_array($term->name, $terms)) {
        $terms[] = $term->name;
      }
    }
  }
  return $terms;
}
/*
 */
function _taxonomy_link_redirect_distill_fields($fields) {
  $results = array();
  foreach($fields as $key => $field) {
    if(is_array($field) && !empty($field)) {
      if(_taxonomy_link_redirect_is_science_field($key) && !in_array($key, $results)) {
        $results[] = $key;
      }
    }
  }
  return $results;
}

function _taxonomy_link_redirect_is_science_field($field) {
  $pattern = "/^field_/";
  $junk = array(
    'field_title_tag',
    'field_science_category'
  );
  return (preg_match($pattern, $field) === 1) && (!in_array($field, $junk));
}


/*
function _taxonomy_link_redirect_clean($str) {
  $strip_field = str_replace('field_', '', $str);
  $url_ready = str_replace('_', '-', $strip_field);
  $clean = substr_replace($str, '', 0, 6);
  $clean = 
  return $url_ready;
}
  */
